version: "3.8"
services:
  server:
    image: board-portal2:latest
    build:
      context: .
      args:
        SERVER_NAME: ${SERVER_NAME}
    container_name: "${PROJECT_NAME}-${PHP_VERSION}"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    links:
      - database:database
    volumes:
      - ./api:/var/www/html/api:rw
      - ./classes:/var/www/html/classes:rw
      - ./public:/var/www/html/public:rw
      - ./views:/var/www/html/views:rw
      - ./loader.php:/var/www/html/loader.php:rw
      - .config.json:/var/www/html/.config.json
      - ./docker/apache/${SERVER_NAME}.conf:/etc/apache2/sites-available/${SERVER_NAME}.conf
      - ./docker/ssl/${SERVER_NAME}.key:/etc/apache2/ssl/${SERVER_NAME}.key
      - ./docker/ssl/${SERVER_NAME}.crt:/etc/apache2/ssl/${SERVER_NAME}.crt
      - ./docker/logs/error.log:/var/log/apache2/error.log
      - ./docker/logs/access.log:/var/log/apache2/other_vhosts_access.log
      - ./docker/logs/debug.txt:/var/www/html/debug.txt
      - ./docker/volumes/cache:/var/www/html/cache
      - ./docker/volumes/demos:/var/www/html/demos
      - ./docker/volumes/sessions:/var/www/html/sessions
  database:
    image: mysql:8
    container_name: "${PROJECT_NAME}-${DATABASE_VERSION}"
    restart: unless-stopped
    ports:
      - "127.0.0.1:3306:3306"
    cpus: 0.5
    cpu_count: 2
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/var/lib/mysql
