version: "3.8"
services:
  server:
    build:
      context: .
      args:
        SERVER_NAME: ${SERVER_NAME}
        APT_PACKAGES: ${APT_PACKAGES}
    container_name: "${PROJECT_NAME}-server"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:${HTTP_PORT}:80"
      - "127.0.0.1:${HTTPS_PORT}:443"
    links:
      - database:database
    volumes:
      - ./api:/var/www/html/api:rw
      - ./classes:/var/www/html/classes:rw
      - ./public:/var/www/html/public:rw
      - ./views:/var/www/html/views:rw
      - ./loader.php:/var/www/html/loader.php:rw
      - .config.json:/var/www/html/.config.json
      - ./docker/apache/${SERVER_NAME}.conf:/etc/apache2/sites-available/${SERVER_NAME}.conf
      - ./docker/logs/error.log:/var/log/apache2/error.log
      - ./docker/logs/access.log:/var/log/apache2/other_vhosts_access.log
      - ./docker/logs/debug.txt:/var/www/html/debug.txt
      - ./docker/php/board.ini:/etc/php/8.1/apache2/conf.d/board.ini
      - ./docker/ssl/${SERVER_NAME}.key:/etc/apache2/ssl/${SERVER_NAME}.key
      - ./docker/ssl/${SERVER_NAME}.crt:/etc/apache2/ssl/${SERVER_NAME}.crt
      - ./docker/volumes/cache:/var/www/html/cache
      - ./docker/volumes/demos:/var/www/html/demos
      - ./docker/volumes/sessions:/var/www/html/sessions
  database:
    image: mysql:8
    container_name: "${PROJECT_NAME}-db"
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - ./docker/volumes/mysql:/var/lib/mysql
      - ./docker/volumes/backups:/backups
