<div id="footer">
    <div class="footerleft">
        Originally developed and designed by <a href="https://github.com/ncla" target="_blank">ncla</a> and <a href="https://github.com/iVerb1" target="_blank">iVerb</a>. Maintained by <a href="https://github.com/NeKzor" target="_blank">NeKz</a>.
    </div>
    <div class="footeright"><a href="javascript:toggleTheme()">Toggle Light/Dark Mode</a></div>
</div>
