version: "3.8"
services:
  server:
    ports:
      - "127.0.0.1:${HTTP_PORT}:80"
      - "127.0.0.1:${HTTPS_PORT}:443"
    volumes:
      - .config.json:/var/www/html/.config.json
      - ./docker/apache/${SERVER_NAME}.conf:/etc/apache2/sites-available/${SERVER_NAME}.conf
      - ./docker/logs/error.log:/var/log/apache2/error.log
      - ./docker/logs/access.log:/var/log/apache2/other_vhosts_access.log
      - ./docker/logs/debug.txt:/var/www/html/debug.txt
      - ./docker/php/board.ini:/etc/php/8.1/apache2/conf.d/board.ini
      - ./docker/volumes/cache:/var/www/html/cache
      - ./docker/volumes/demos:/var/www/html/demos
      - ./docker/volumes/sessions:/var/www/html/sessions
  database:
    ports:
      - "127.0.0.1:${DATABASE_PORT}:${DATABASE_PORT}"
